---
- name: Testing andrewrothstein.kubernetes_helm
  hosts: all
  tasks:
    - name: Installing andrewrothstein.kubernetes_helm
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
    - name: Executing 'helm version'
      ansible.builtin.command: /usr/local/bin/helm version
      changed_when: false
      register: kubernetes_helm_test_output
    - name: Output of 'helm version'
      ansible.builtin.debug:
        msg: '{{ kubernetes_helm_test_output.stdout }}'
