---
- name: Install brew package
  become: '{{ kubernetes_helm_privilege_escalate | default(False) }}'
  become_user: root
  community.general.homebrew:
    name: '{{ kubernetes_helm_brew_package }}'
    state: present
