---
- name: Check for installation in {{ kubernetes_helm_install_dir }}
  become: true
  ansible.builtin.stat:
    path: '{{ kubernetes_helm_install_dir }}'
  changed_when: false
  register: kubernetes_helm_binary_dir

- name: Downloading and Installing...
  when: not kubernetes_helm_binary_dir.stat.exists
  block:
    - name: Downloading {{ kubernetes_helm_url }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ kubernetes_helm_url }}'
        dest: '{{ kubernetes_helm_tmp_archive }}'
        checksum: '{{ kubernetes_helm_checksum }}'
        mode: '644'

    - name: Mkdir {{ kubernetes_helm_install_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ kubernetes_helm_install_dir }}'
        state: directory
        mode: '755'

    - name: Unarchive {{ kubernetes_helm_tmp_archive }} to {{ kubernetes_helm_install_dir }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ kubernetes_helm_tmp_archive }}'
        dest: '{{ kubernetes_helm_install_dir }}'
        creates: '{{ kubernetes_helm_install_subdir }}'
  always:
    - name: Cleanup {{ kubernetes_helm_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ kubernetes_helm_tmp_archive }}'
        state: absent

- name: Creating link in {{ kubernetes_helm_link_bin_dir }} to {{ kubernetes_helm_install_exe }}
  become: true
  become_user: root
  with_items: '{{ kubernetes_helm_links }}'
  ansible.builtin.file:
    src: '{{ kubernetes_helm_install_exe }}'
    dest: '{{ item }}'
    state: link
